// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARh-dOsV37OJVuwLyzHDBx8D_MFvjtqqk',
    appId: '1:49177814530:web:20e461e1d243b9a681e91b',
    messagingSenderId: '49177814530',
    projectId: 'test-mj-5',
    authDomain: 'test-mj-5.firebaseapp.com',
    storageBucket: 'test-mj-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5A-Jtyi1KW_Qvf3Oe2sH3xGbkAMqpqLM',
    appId: '1:49177814530:android:7d50081699d9f1b781e91b',
    messagingSenderId: '49177814530',
    projectId: 'test-mj-5',
    storageBucket: 'test-mj-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMe6k_lVP1hbSnU8EHt_nNBLVeEOPhxOw',
    appId: '1:49177814530:ios:3bc58a5cf1d5bc6b81e91b',
    messagingSenderId: '49177814530',
    projectId: 'test-mj-5',
    storageBucket: 'test-mj-5.appspot.com',
    iosBundleId: 'com.example.front.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMe6k_lVP1hbSnU8EHt_nNBLVeEOPhxOw',
    appId: '1:49177814530:ios:442e0a20d594eb8d81e91b',
    messagingSenderId: '49177814530',
    projectId: 'test-mj-5',
    storageBucket: 'test-mj-5.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARh-dOsV37OJVuwLyzHDBx8D_MFvjtqqk',
    appId: '1:49177814530:web:659a3cc2d52d3cca81e91b',
    messagingSenderId: '49177814530',
    projectId: 'test-mj-5',
    authDomain: 'test-mj-5.firebaseapp.com',
    storageBucket: 'test-mj-5.appspot.com',
  );
}
