runtime: python39

# split the app into multiple services
service: front

handlers:
  - url: /
    static_files: web/index.html
    upload: web/index.html

  - url: /(.*)
    static_files: web/\1
    upload: web/(.*)